# Docker Compose file for Synapse with TimescaleDB and Redis
name: synapse_timescaledb_redis
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: synapse_TimescaleDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: synapse_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - timescale-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: synapse_Redis
    restart: always
    ports:
      - "6379:6379"

  coredb:
    image: postgres:15
    container_name: synapse_CoreDB
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: coreadmin
      POSTGRES_PASSWORD: coreadminpassword
    volumes:
      - coredb-data:/var/lib/postgresql/data

volumes:
  timescale-data:
  coredb-data:
